theme: jekyll-theme-cayman
# Site settings
title: Anthony Lonsdale's Portfolio
description: A Collection of Personal Projects and Programs
baseurl: "/home"

# User settings
username: Anthony Lonsdale
user_description: 
user_title: Full Time Physics Undergraduate
emailaddress: alons3253@gmail.com
resume-url:  file:///C:/Users/fabio/OneDrive/Documents/Business%20Documents/Application%20Documents/resume.pdf
github-url:  https://github.com/alons3253/
linkedin-url: https://www.linkedin.com/in/anthonymlonsdale/
